### ISSUE TITLE
Issue converting ppttc to pptx

### ISSUE THREAD

**Issue by PythonDoubts** [duarteocarmo/think-cell#2]
Hi,

When I'm trying to convert ppttc to pptx in my Python code. I'm facing issue to run the command on cmd using Python.

I have created an API to run my code to update Thinkcell data. If say multiple users are running the API concurrently, I want the output pptx to have timestamp as part of the pptx file name

But I'm not able to add timestamp as part of the command to convert ppttc to pptx. Basically, I'm not able to add variable as part of cmd command
current_timestamp=datetime.now()

If you can help me with that.

Following is the working  syntax in python which is converting the ppttc to pptx.
cmd='""C:\\Program Files (x86)\\think-cell\\ppttc.exe" "C:\\Users\\Dhingra_akshay\\Desktop\\Thinkcell_Template.ppttc" -o "C:\\Users\\Dhingra_akshay\\Desktop\\Thinkcell_Template_1.pptx""'

os.system(cmd)

**Comment by duarteocarmo** [comment]
Hey there, thanks for your message. Unfortunately, to help you with this I would need access to the API you have created and the rest of the code. 

I think this is not very aligned with the current scope of the project. 

Thanks for your understanding!
