### ISSUE TITLE
DataFrameError: You did not pass a valid Pandas DataFrame

### ISSUE THREAD

**Issue by martijnnh** [duarteocarmo/think-cell#5]
Hi,

First of all, I really appreciate the work you have put into this feature.

I am new to GitHub, not sure whether this is the right wat to reach out. Please excuse me if I am making any rookie errors.

When I am trying to run the code below an error "DataFrameError: You did not pass a valid Pandas DataFrame" is raised.

Code:
from thinkcell import Thinkcell

template_name = "simple-template.pptx"
chart_name = "Chart1"
filename = "simple-example.ppttc"
dataframe = pd.DataFrame(
    columns=["Company", "Ads", "Revenue", "Losses"],
    data=[["Amazon", 1, 11, 14], ["Slack", 8, 2, 15], ["Ford", 1, 2, 12]],
)

tc = Thinkcell() # create thinkcell object
tc.add_template(template_name) # add your template
tc.add_chart_from_dataframe(
    template_name=template_name,
    chart_name=chart_name,
    dataframe=dataframe,
) # add your dataframe

tc.save_ppttc(filename=filename)

Error:
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\thinkcell\thinkcell.py in add_chart_from_dataframe(self, template_name, chart_name, dataframe)
    192         try:
--> 193             categories = dataframe.columns.to_list()[1:]
    194             assert isinstance(categories, list)

AttributeError: 'Index' object has no attribute 'to_list'

During handling of the above exception, another exception occurred:

DataFrameError                            Traceback (most recent call last)
<ipython-input-118-c79071a582b3> in <module>()
     14     template_name=template_name,
     15     chart_name=chart_name,
---> 16     dataframe=dataframe,
     17 ) # add your dataframe
     18 

C:\ProgramData\Anaconda3\lib\site-packages\thinkcell\thinkcell.py in add_chart_from_dataframe(self, template_name, chart_name, dataframe)
    196             assert isinstance(data, list)
    197         except (AttributeError, AssertionError):
--> 198             raise DataFrameError("You did not pass a valid Pandas DataFrame")
    199 
    200         try:

DataFrameError: You did not pass a valid Pandas DataFrame

**Comment by duarteocarmo** [comment]
Hey, try this

```python
from thinkcell import Thinkcell
import pandas as pd

template_name = "simple-template.pptx"
chart_name = "Chart1"
filename = "simple-example.ppttc"
dataframe = pd.DataFrame(
    columns=["Company", "Ads", "Revenue", "Losses"],
    data=[["Amazon", 1, 11, 14], ["Slack", 8, 2, 15], ["Ford", 1, 2, 12]],
)

tc = Thinkcell() # create thinkcell object
tc.add_template(template_name) # add your template
tc.add_chart_from_dataframe(
    template_name=template_name,
    chart_name=chart_name,
    dataframe=dataframe,
) # add your dataframe

tc.save_ppttc(filename=filename)
```

**Comment by martijnnh** [comment]
Hi @duarteocarmo,

Same error is raised when running the provided code. Any other suggestion how to fix?

**Comment by duarteocarmo** [comment]
Hey, sorry - but I cannot reproduce your issue. 

I would try to reinstall in a new virtual environment, making sure that you are using a supported python version. I will also leave you an example of my running code below. And I hope you get it working!

The library is tested in for python versions 3.6, 3.7, 3.8 and 3.9, through most operating systems. We also test this use case whenever we release, and[ those tests are all passing.](https://github.com/duarteocarmo/think-cell/actions/runs/1283963510) 


```bash
(.env) [durc1211:~/Repos/test]$ pip freeze
numpy==1.21.2
pandas==1.3.3
python-dateutil==2.8.2
pytz==2021.1
six==1.16.0
thinkcell==21.10.12

(.env) [durc1211:~/Repos/test]$ cat test.py
from thinkcell import Thinkcell
import pandas as pd

template_name = "simple-template.pptx"
chart_name = "Chart1"
filename = "simple-example.ppttc"
dataframe = pd.DataFrame(
    columns=["Company", "Ads", "Revenue", "Losses"],
    data=[["Amazon", 1, 11, 14], ["Slack", 8, 2, 15], ["Ford", 1, 2, 12]],
)

tc = Thinkcell()  # create thinkcell object
tc.add_template(template_name)  # add your template
tc.add_chart_from_dataframe(
    template_name=template_name,
    chart_name=chart_name,
    dataframe=dataframe,
)  # add your dataframe

tc.save_ppttc(filename=filename)

(.env) [durc1211:~/Repos/test]$ python test.py

(.env) [durc1211:~/Repos/test]$ l
total 8.0K
drwxr-xr-x  5 durc1211 staff  160 Sep 29 09:51 .
drwxr-xr-x 34 durc1211 staff 1.1K Sep 28 15:10 ..
drwxr-xr-x  6 durc1211 staff  192 Sep 29 09:45 .env
-rw-r--r--  1 durc1211 staff  363 Sep 29 09:51 simple-example.ppttc
-rw-r--r--  1 durc1211 staff  573 Sep 29 09:50 test.py
(.env) [durc1211:~/Repos/test]$

```
